# Generated by Django 2.1.2 on 2022-05-29 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='receta',
            fields=[
                ('idreceta', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de cada receta')),
                ('titulo', models.CharField(max_length=20, verbose_name='Titulo de la receta')),
                ('imagen', models.ImageField(null=True, upload_to='recetas')),
                ('parrafo', models.CharField(max_length=1200, verbose_name='Descripcion de la receta')),
            ],
        ),
        migrations.CreateModel(
            name='usuario',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, verbose_name='ID de usuario')),
                ('nombre', models.CharField(max_length=20, verbose_name='Nombre usuario')),
                ('apellido', models.CharField(max_length=34, verbose_name='Apellido usuairo')),
                ('mail', models.CharField(max_length=60, verbose_name='email del usuario')),
                ('contrasena', models.CharField(max_length=16, verbose_name='contrasena de usuario')),
            ],
        ),
        migrations.AddField(
            model_name='receta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario'),
        ),
    ]
