# Generated by Django 2.2.10 on 2022-06-07 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_receta_idreceta_alter_receta_usuario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receta',
            name='parrafo',
            field=models.TextField(verbose_name='Descripcion de la receta'),
        ),
    ]
